version: "3.3"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    image: usokolov692/frontend:main
    ports:
      - "80:80"
    depends_on:
      - backend
